// Copyright 2024 - Tomas Bartipan
// Licensed under MIT license - See License.txt for details.
// Special credits go to :
// Temaran (compute shader tutorial), TheHugeManatee (original concept) and Ryan Brucks(original raymarching code).

#include "/Engine/Private/Common.ush"

RWTexture2D<float> ClearTextureRW;

float ClearValue;

[numthreads(16, 16, 1)]
void MainComputeShader(uint2 ThreadId : SV_DispatchThreadID)
{
    ClearTextureRW[int2(ThreadId.x, ThreadId.y)] = ClearValue;
}
