// Copyright 2024 - Tomas Bartipan
// Licensed under MIT license - See License.txt for details.
// Special credits go to :
// Temaran (compute shader tutorial), TheHugeManatee (original concept) and Ryan Brucks(original raymarching code).

//
// This shader generates an Octree acceleration structure's intermediate levels.
//

// The Octree Higher Mip that we're populating in this shader.
RWTexture3D<float> OctreeHigherMip;

// The Octree Lower Mip we're reading data from
Texture3D<float> OctreeLowerMip;

int NodeSize = 2;

[numthreads(1, 1, 1)]
void MainComputeShader(uint3 VoxelLoc : SV_DispatchThreadID)
{
    // Position in the upper Mip texture index space.
    int3 Pos = int3(VoxelLoc.x, VoxelLoc.y, VoxelLoc.z);
    // Position in the lower Mip texture index space. 
    int3 LowerMipPos = Pos * NodeSize;
    float MaxValue = 0.0;
    
    // Copy the data from the input volume to maximal resolution mip first.
    for (int x = 0; x < NodeSize; x++)
    {
        for (int y = 0; y < NodeSize; y++)
        {
            for (int z = 0; z < NodeSize; z++)
            {
                int3 LocalPos = int3(x, y, z);
                int3 ActualPos = LowerMipPos + LocalPos;
                // For now, just use max to visualize. #TODO bitmask
                MaxValue = max(MaxValue, OctreeLowerMip.Load(int4(ActualPos, 0), 0).r);
            }
        }
    }
    OctreeHigherMip[Pos] = MaxValue;
}
