// Copyright 2024 - Tomas Bartipan
// Licensed under MIT license - See License.txt for details.
// Special credits go to :
// Temaran (compute shader tutorial), TheHugeManatee (original concept) and Ryan Brucks(original raymarching code).

#include "RaymarcherCommon.usf"
#include "RaymarchMaterialCommon.usf"
#include "WindowedSampling.usf"

int3 GetVolumeLoadingDimensions(Texture3D Volume)
{
    int x, y, z;
    Volume.GetDimensions(x, y, z);
    // Decrease dimensions by 1, because with any UVW coord being == 1, we would load one after the array length
    // E.G - with X dimension == 2, U == 1, we want to sample x[1], not x[2] (as that doesn't exist)
    return int3(x - 1, y - 1, z - 1);
}

// Performs one raymarch step and accumulates the result to the existing Accumulated Light Energy.
// Notice "Material.Clamp_WorldGroupSettings" used as a sampler. These are UE shared samplers.
void AccumulateWindowedRaymarchStep(inout float4 AccumulatedLightEnergy, float3 CurPos, Texture3D DataVolume, SamplerState DataVolumeSampler,
                                 Texture2D TF, Texture3D LightVolume, float StepSize,
                                 float4 WindowingParams)
{
    float4 ColorSample = SampleWindowedVolumeStep(CurPos, StepSize, DataVolume, DataVolumeSampler,
                                               TF, Material.Clamp_WorldGroupSettings, WindowingParams);
    
    // Get lighting information from illumination volume for current position and
    // Multiply sampled color with light color to adjust intensity according to light strength.
	ColorSample.rgb = ColorSample.rgb * LightVolume.SampleLevel(Material.Wrap_WorldGroupSettings, saturate(CurPos), 0).r;
	// Accumulate current colored sample to the final values.
    AccumulateLightEnergy(AccumulatedLightEnergy, ColorSample);
}

// Performs lit raymarch for the current pixel. The lighting information is taken from a precomputed light volume.
float4 PerformWindowedLitRaymarch(Texture3D DataVolume, // Data Volume 
                              SamplerState DataVolumeSampler,
                              Texture2D TF, // Transfer function texture.
                              Texture3D LightVolume, // Light Volume  
                              float3 CurPos, float Thickness, // CurPos = Entry Position, Thickness is thickness of cube along the ray. Both in UVW space.
                              float StepCount, // How many steps we should take. Actual number of steps taken is StepCount * Thickness.
                              float4 WindowingParams,
                              FMaterialPixelParameters MaterialParameters) // Material Parameters provided by UE.
{
    // StepSize in UVW is inverse to StepCount.
    float StepSize = 1 / StepCount;
    // Actual number of steps to take to march through the full thickness of the cube at the ray position.
    float FloatActualSteps = StepCount * Thickness;
    // Number of full steps to take.
    int MaxSteps = floor(FloatActualSteps);
    // Size of the last (not a full-sized) step.
    float FinalStep = frac(FloatActualSteps);
    
    // Get camera vector in local space and multiply it by step size.
    float3 LocalCamVec = -normalize(mul(MaterialParameters.CameraVector, LWCHackToFloat(GetPrimitiveData(MaterialParameters.PrimitiveId).WorldToLocal))) * StepSize;
    // Get step size in local units to get consistent opacity at different volume scale and to be consistent with compute shaders' opacity calculations.
    float StepSizeWorld = VOLUME_DENSITY * StepSize;
    // Initialize accumulated light energy.
    float4 LightEnergy = 0;
    // Jitter Entry position to avoid artifacts.
    JitterEntryPos(CurPos, LocalCamVec, MaterialParameters);
   
    int i = 0;
    for (i = 0; i < MaxSteps; i++)
    {
	    CurPos += LocalCamVec; // Because we jitter only "against" the direction of LocalCamVec, start marching before first sample.
    	AccumulateWindowedRaymarchStep(LightEnergy, CurPos, DataVolume, DataVolumeSampler,
			TF, LightVolume, StepSizeWorld, WindowingParams);

    	// Exit early if light energy (opacity) is already very high (so future steps would have almost no impact on color).
    	if (LightEnergy.a > 0.95f)
    	{
    		LightEnergy.a = 1.0f;
    		break;
    	};
    }

    // Handle FinalStep (only if we went through all the previous steps and the final step size is above zero)
    if (i == MaxSteps && FinalStep > 0.0f)
    {
	    CurPos += LocalCamVec * (FinalStep);
    	// If the final step is clipped, don't do anything.
    	AccumulateWindowedRaymarchStep(LightEnergy, CurPos, DataVolume, DataVolumeSampler,
		TF, LightVolume, VOLUME_DENSITY * FinalStep, WindowingParams);
    }

    return LightEnergy;
}

bool IsInsideVolume(float3 CurPos)
{
    return (CurPos.x) < 1 && (CurPos.y) < 1 && (CurPos.z) < 1 &&
           (CurPos.x) > 0 && (CurPos.y) > 0 && (CurPos.z) > 0;
}

bool GetNextSignificantPosition(const Texture3D DataVolume, const Texture3D OctreeVolume, const float3 LocalCamVec,
    const uint UintWindowMask, inout float3 CurPos)
{
    // Set to the mip number with worst detail.
	const int MaxPossibleMip = 3;
    const int MinPossibleMip = 0;
	// Current mip where the algorithm raymarch data in octree.
    float CurrentMip = 0;
    float OctreeMipCount = 0;
    
	// Get the volume depth for later use when recalculating coordinates.
	float3 DataVolumeSize;
	DataVolume.GetDimensions(DataVolumeSize.x, DataVolumeSize.y, DataVolumeSize.z);
	
	float3 OctreeSize;
    OctreeVolume.GetDimensions(OctreeSize.x, OctreeSize.y, OctreeSize.z);
	// Copy the octree depth on mip level 0 for use when recalculating to correct texture coordinates.
    float3 OctreeSizeLowest = OctreeSize;

    float3 DataVolumeSizeToLowestOctreeSize = DataVolumeSize / OctreeSizeLowest;

    // Move the CurPos one step ahead (that's the minimal-distance next position).
    CurPos += LocalCamVec;
    while(IsInsideVolume(CurPos)) // TODO Optimize this condition maybe?
    {
        // Get the correct width, height and depth for current octree mip.
        OctreeVolume.GetDimensions(CurrentMip, OctreeSize.x, OctreeSize.y, OctreeSize.z, OctreeMipCount); // TODO calculate size from octree mip directly
        // Because of different sizes of Volume vs Octree, need to adjust where we sample from.
        // (Volume can be arbitrary size, octree is always nearest higher power of 2)
        float3 AdjustedSize = OctreeSize * DataVolumeSizeToLowestOctreeSize;

        // Calculate the correct position in octree. The Z coordinate needs to be multiplied by ratio of the base volume depth vs base octree volume depth.
        // Multiply all the values by their respective volume size to get actual texel coordinates instead af UV coordinates.
        int3 VoxelPos = int3(CurPos * AdjustedSize);
        
        // Get the bit mask saved in octree volume and check it against current window. In case the and operator results is true, the
        // value in the volume should be used. If not, find the next position in volume upper mip and starts again. 
        const uint BitMask = asuint(OctreeVolume.Load(int4(VoxelPos, CurrentMip), 0).r);
        if (!(BitMask & UintWindowMask))
        {
            // Get the box min values calculated in UV coordinates.
            float3 BoxMin = VoxelPos / AdjustedSize;
            // Get the box max values calculated in UV coordinates.
            float3 BoxMax = (VoxelPos + 1) / AdjustedSize;;
            float2 EntryTimes = float2(0,0);
            if (CheckedRayAABBIntersection(CurPos, LocalCamVec, BoxMin, BoxMax, EntryTimes))
            {
                // Use ceil to align with the requested step size.
                CurPos += LocalCamVec * ceil(EntryTimes.y);

                // Current mip does not have useful data, move one mip above for next cycle (if possible).
                CurrentMip = clamp(CurrentMip + 1, CurrentMip, MaxPossibleMip);
                continue;
            }
            return false;
        }

        // We're at the lowest mip and still hitting the mask -> start sampling normally
        if (CurrentMip == MinPossibleMip)
        {
            return true;
        }

        // Step down to us mip with better resolution in next iteration.
        CurrentMip -= 1;
    }
    // No position with usefull data found or the ray reach the final destination. Return.
    return false;
}

// Performs octree raymarch for the current pixel.
float4 PerformWindowedRaymarchOctree(Texture3D DataVolume, // Data Volume 
                              SamplerState DataVolumeSampler,
                              Texture2D TF, // Transfer function texture.
                              float3 EntryPos, float Thickness, // CurPos = Entry Position, Thickness is thickness of cube along the ray. Both in UVW space.
                              float StepCount, // How many steps we should take. Actual number of steps taken is StepCount * Thickness.
                              float4 WindowingParams,
                              Texture3D OctreeVolume,
                              SamplerState OctreeVolumeSampler,
                              Texture3D LightVolume,
                              SamplerState LightVolumeSampler,
                              float4 WindowMask,
                              FMaterialPixelParameters MaterialParameters) // Material Parameters provided by UE.
{
    // StepSize in UVW is inverse to StepCount.
    float StepSize = 1 / StepCount;

    // Get camera vector in local space and multiply it by step size.
    float3 LocalCamVec = -normalize(mul(MaterialParameters.CameraVector, LWCHackToFloat(GetPrimitiveData(MaterialParameters.PrimitiveId).WorldToLocal))) * StepSize;
	
    // Get step size in local units to get consistent opacity at different volume scale and to be consistent with compute shaders' opacity calculations.
    float StepSizeWorld = VOLUME_DENSITY * StepSize;

    // Initialize accumulated light energy.
    float4 LightEnergy = 0;

    // Jitter Entry position to avoid artifacts.
    JitterEntryPos(EntryPos, LocalCamVec, MaterialParameters);

    // Get the bit mask for the current TransferFunction with the current window width/center.
    uint UintWindowMask = asuint(WindowMask.r);
    // The distance the raymarch must pass to calculate required data.

    float3 CurPos = EntryPos;
    while(length((CurPos - EntryPos)) < Thickness)
    {
        bool PositionFound = GetNextSignificantPosition(DataVolume, OctreeVolume, LocalCamVec, UintWindowMask, CurPos);
        if(!PositionFound)
            break;

        AccumulateWindowedRaymarchStep(LightEnergy, CurPos, DataVolume, DataVolumeSampler, TF, LightVolume, StepSizeWorld, WindowingParams);

        // Exit early if light energy (opacity) is already very high (so future steps would have almost no impact on color).
        if (LightEnergy.a > 0.95f)
        {
            LightEnergy.a = 1.0f;
            break;
        };
    }
    return LightEnergy;
}

// Performs debug raymarch 1 for the current pixel.
float4 PerformDebug1Raymarch(Texture3D DataVolume, // Data Volume 
                     SamplerState DataVolumeSampler,
                     Texture2D TF, // Transfer function texture.
                     float3 EntryPos, float Thickness, // CurPos = Entry Position, Thickness is thickness of cube along the ray. Both in UVW space.
                     float StepCount, // How many steps we should take. Actual number of steps taken is StepCount * Thickness.
                     float4 WindowingParams,
                     Texture3D OctreeVolume,
                     SamplerState OctreeVolumeSampler,
                     Texture3D LightVolume,
                     SamplerState LightVolumeSampler,
                     float4 WindowMask,
                     FMaterialPixelParameters MaterialParameters) // Material Parameters provided by UE.
{
    // StepSize in UVW is inverse to StepCount.
    float StepSize = 1 / StepCount;

    // Get camera vector in local space and multiply it by step size.
    float3 LocalCamVec = -normalize(mul(MaterialParameters.CameraVector, LWCHackToFloat(GetPrimitiveData(MaterialParameters.PrimitiveId).WorldToLocal))) * StepSize;
	
    // Get step size in local units to get consistent opacity at different volume scale and to be consistent with compute shaders' opacity calculations.
    float StepSizeWorld = VOLUME_DENSITY * StepSize;

    // Initialize accumulated light energy.
    float4 LightEnergy = float4(0.0f, 0.0f, 0.0f, 1.0f);

    // Jitter Entry position to avoid artifacts.
    JitterEntryPos(EntryPos, LocalCamVec, MaterialParameters);

    // Get the bit mask for the current TransferFunction with the current window width/center.
    uint UintWindowMask = asuint(WindowMask.r);
    // The distance the raymarch must pass to calculate required data.

    float3 CurPos = EntryPos;
    while(length((CurPos - EntryPos)) < Thickness)
    {
        bool PositionFound = GetNextSignificantPosition(DataVolume, OctreeVolume, LocalCamVec, UintWindowMask, CurPos);
        if(!PositionFound)
            break;
        LightEnergy.r += 0.01;
    }
    return LightEnergy;
}

// Performs debug raymarch 2 for the current pixel.
float4 PerformDebug2Raymarch(Texture3D DataVolume, // Data Volume 
                     SamplerState DataVolumeSampler,
                     Texture2D TF, // Transfer function texture.
                     float3 EntryPos, float Thickness, // CurPos = Entry Position, Thickness is thickness of cube along the ray. Both in UVW space.
                     float StepCount, // How many steps we should take. Actual number of steps taken is StepCount * Thickness.
                     float4 WindowingParams,
                     Texture3D OctreeVolume,
                     SamplerState OctreeVolumeSampler,
                     Texture3D LightVolume,
                     SamplerState LightVolumeSampler,
                     float4 WindowMask,
                     FMaterialPixelParameters MaterialParameters) // Material Parameters provided by UE.
{
    // StepSize in UVW is inverse to StepCount.
    float StepSize = 1 / StepCount;

    // Get camera vector in local space and multiply it by step size.
    float3 LocalCamVec = -normalize(mul(MaterialParameters.CameraVector, LWCHackToFloat(GetPrimitiveData(MaterialParameters.PrimitiveId).WorldToLocal))) * StepSize;
	
    // Get step size in local units to get consistent opacity at different volume scale and to be consistent with compute shaders' opacity calculations.
    float StepSizeWorld = VOLUME_DENSITY * StepSize;

    // Initialize accumulated light energy.
    float4 LightEnergy = 0;

    // Jitter Entry position to avoid artifacts.
    JitterEntryPos(EntryPos, LocalCamVec, MaterialParameters);

    // Get the bit mask for the current TransferFunction with the current window width/center.
    uint UintWindowMask = asuint(WindowMask.r);
    // The distance the raymarch must pass to calculate required data.

    float3 CurPos = EntryPos;
    while(length((CurPos - EntryPos)) < Thickness)
    {
        bool PositionFound = GetNextSignificantPosition(DataVolume, OctreeVolume, LocalCamVec, UintWindowMask, CurPos);
        if(!PositionFound)
            break;

        AccumulateWindowedRaymarchStep(LightEnergy, CurPos, DataVolume, DataVolumeSampler, TF, LightVolume, StepSizeWorld, WindowingParams);

        // Exit early if light energy (opacity) is already very high (so future steps would have almost no impact on color).
        if (LightEnergy.a > 0.95f)
        {
            LightEnergy.a = 1.0f;
            break;
        };
    }
    return LightEnergy;
}

// Performs lit raymarch for the current pixel. The lighting information is taken from a precomputed light volume.
float4 PerformWindowedIntensityRaymarch(Texture3D DataVolume, // Data Volume 
                              float3 CurPos, float Thickness, // Position of ray entry to cube and thickness in UVW coords.
                              float StepCount, // Number of steps to take if Thickness is 1. 
                              float4 WindowingParams,
                              FMaterialPixelParameters MaterialParameters)                      // Material Parameters
{
    // StepSize in UVW is inverse to StepCount.
    float StepSize = 1 / StepCount;
    // Actual number of steps to take to march through the full thickness of the cube at the ray position.
    float FloatActualSteps = StepCount * Thickness;
    // Number of full steps to take.
    int MaxSteps = floor(FloatActualSteps);
    // Size of the last (not a full-sized) step.
    float FinalStep = frac(FloatActualSteps);
    
    // Get camera vector in local space and multiply it by step size.
    float3 LocalCamVec = -normalize(mul(MaterialParameters.CameraVector, LWCHackToFloat(GetPrimitiveData(MaterialParameters.PrimitiveId).WorldToLocal))) * StepSize;
    // Jitter Entry position to avoid artifacts.
    JitterEntryPos(CurPos, LocalCamVec, MaterialParameters);
   
    int i = 0;
    for (i = 0; i < MaxSteps; i++)
    {
	    CurPos += LocalCamVec; // Because we jitter only "against" the direction of LocalCamVec, start marching before first sample.
    	float DataValue = DataVolume.SampleLevel(Material.Clamp_WorldGroupSettings, saturate(CurPos), 0).r;
  
    	// WindowingParams.x == Center, WindowingParams.y = Width
    	float TFPos = clamp(GetTransferFuncPosition(DataValue, WindowingParams.x, WindowingParams.y), 0, 1);

    	return float4(TFPos, TFPos, TFPos, 1);
    }

    // Handle FinalStep (if the final step size is above zero).
    if (FinalStep > 0.0f)
    {
	    CurPos += LocalCamVec * (FinalStep);
    	float DataValue = DataVolume.SampleLevel(Material.Clamp_WorldGroupSettings, CurPos, 0).r;
  
    	// WindowingParams.x == Center, WindowingParams.y = Width
    	float TFPos = clamp(GetTransferFuncPosition(DataValue, WindowingParams.x, WindowingParams.y), 0, 1);

    	return float4(TFPos, TFPos, TFPos, 1);
    }
    
    // Didn't hit anything
    return float4(0.0, 0.0, 0.0, 0.0);
}